spring:
  application:
    name: producer

  cloud:
    function:
      definition: sendRiderLocation
    stream:
      function:
        definition: sendRiderLocation
      bindings:
        sendRiderLocation-out-0:
          destination: new-topic
          content-type: application/json
      poller:
        fixed-delay: 5000
      kafka:
        binder:
          brokers: localhost:9092

#  kafka:
#    bootstrap-servers: localhost:9092
#
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#
#
#  cloud:
#    function:
#      definition: uppercase
#    function.web.path: /uppercase